title: "Rumeysa Hanife Kars"
author: "Rumeysa Hanife Kars"
description: "Rumeysa Hanife Kars's Personal Web Site"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "article.pdf", title: "Publications"}
  - {file: "CV_RHK.pdf", title: "CV"}
  - {file: "README.md", title: "About me"}
  - {file: "blog.md", title: "Blog"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:hanifekars@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/rumeysakars"}
  - {title: Linkedin, icon: rss, url: "https://www.linkedin.com/in/rumeysa-/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
